// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputElements': string;
  'submitButton': string;
  'textBox': string;
}
export const cssExports: CssExports;
export default cssExports;
