// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'todoListItem': string;
  'todoListItemCrossedOut': string;
}
export const cssExports: CssExports;
export default cssExports;
